spring.application.name=login_signup

#Database configuration
#spring.datasource.url=jdbc:sqlserver://kiarie.database.windows.net:1433;database=free-sql-db-2639964;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=kiarie@kiarie
spring.datasource.password=ANnwPaYKHWjK6!q

#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# h2 web console
spring.h2.console.enabled=true

google.client.id=943861695899-ldjcl19tivb3tpqahbeururrnllu25ql.apps.googleusercontent.com

jwt.secret=mySuperSecureJwtSecretKeyThatIsAtLeast32CharactersLong

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000